# This file was generated by GoReleaser. DO NOT EDIT.
cask "quiver" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/quiver"]
    end
  end

  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "33046af412fc78f4653ecc5ed74d1f0f329d366c883b7298f5dcc2f6e411cd86"
      url "https://github.com/built-for-devs/quiver/releases/download/v#{version}/quiver_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd7cef0fb1d3efb3e3b6827fd54afeab88d84d1fa4969c88a4a86c06c946ee6d"
      url "https://github.com/built-for-devs/quiver/releases/download/v#{version}/quiver_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c70a36e9161fac30c8784656a850d65e07ae8d88d333aa66fc7bcc39fbe01bfa"
      url "https://github.com/built-for-devs/quiver/releases/download/v#{version}/quiver_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "feac24ddcd975ecb38045650076616737e67f610d61245991220df02bcdd4396"
      url "https://github.com/built-for-devs/quiver/releases/download/v#{version}/quiver_linux_amd64.tar.gz"
    end
  end

  name "quiver"
  desc "Command-line client for Quiver"
  homepage "https://quivergtm.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quiver"

  # No zap stanza required
end
